name: Titanic_Space
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas=2.1.3
  - scikit-learn=1.5.1
  - pip=23.2.1
  - jupyterlab=4.3.2
  - ydata-profiling
  - ipywidgets=8.1.5
